# -*- coding: utf-8 -*-
"""Personal_Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BosjBiO0zrDW_F8ivt9qkjOnW_yRDwTm

## Day 1: Hello World

### Subtask:
Create a Python script that prints 'Hello, World!' to the console.
"""

print("Hello, World!")

"""## Day 2: Add User Input

### Subtask:
Modify the script to prompt the user for their name and age using input() statements and store them in variables.

"""

name = input("Enter your name: ")
age = input("Enter your age: ")

"""## Day 3: Welcome Message

### Subtask:
Enhance the script to display a personalized welcome message using an f-string, incorporating the user's name and age.

"""

name = input("Enter your name: ")
age = input("Enter your age: ")

print(f"Welcome {name}! You are {age} years old.")

"""## Day 4: Enhance Program

### Subtask:
Further enhance the script by adding more questions (e.g., city, favorite hobby) and improving the output formatting for better readability.

"""

name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
hobby = input("Enter your favorite hobby: ")

print("\n--- User Information ---")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Favorite Hobby: {hobby}")
print("------------------------\nThank you for providing your details!")

"""## Day 5: Finalize & Test

### Subtask:
Review the entire script, fix any potential errors, add comments to explain the code, and ensure it runs as expected to create the final version.

"""

# This script collects user information and displays it in a formatted manner.

# --- User Input Section ---
# Prompt the user to enter their name and store the input in the 'name' variable.
name = input("Enter your name: ")

# Prompt the user to enter their age and store the input in the 'age' variable.
age = input("Enter your age: ")

# Prompt the user to enter their city and store the input in the 'city' variable.
city = input("Enter your city: ")

# Prompt the user to enter their favorite hobby and store the input in the 'hobby' variable.
hobby = input("Enter your favorite hobby: ")

# --- Output Section ---
# Print a header to clearly separate the input prompts from the displayed information.
print("\n--- User Information ---")

# Display the collected name using an f-string for easy formatting.
print(f"Name: {name}")

# Display the collected age.
print(f"Age: {age}")

# Display the collected city.
print(f"City: {city}")

# Display the collected favorite hobby.
print(f"Favorite Hobby: {hobby}")

# Print a footer to conclude the output section and a thank you message.
print("------------------------\nThank you for providing your details!")